### ISSUE TITLE
Import from existing crontab instance in same system

### ISSUE THREAD

**Issue by JeganathanVelu** [alseambusher/crontab-ui#10]
Hi

I installed cron tool first in ubuntu 14.04 headless server and scheduled a job. Post which I installed crontab-ui.

I am not able to see the already scheduled job. Does crontab-ui refers to existing crontab file by default or do i need to do something specific to view existing scheduled jobs.

Thanks for your help and a great tool

**Comment by alseambusher** [comment]
Unfortunately importing existing crontab is not yet been implemented :(

**Comment by alseambusher** [comment]
Feature added [@b1a1c21](https://github.com/alseambusher/crontab-ui/commit/b1a1c214e474308e917364ec663d46af1ff25b7a).
