### ISSUE TITLE
The program stops running

### ISSUE THREAD

**Issue by Perterually** [alseambusher/crontab-ui#101]
- [ ] npm version 6.8.0
- [ ] node version v11.8.0
- [ ] system info ubuntu 16.04
![Screenshot_2019-05-27_17-26-52](https://user-images.githubusercontent.com/12246868/58411649-54ac9100-80a7-11e9-9b46-459d7dce9422.png)

**Comment by alseambusher** [comment]
probably there is some problem in the crontab db file. Delete the files in crontabs folder and try again

**Comment by Perterually** [comment]
Thank you, you are right.
