### ISSUE TITLE
Add HTTP basic auth option via ENV variables.

### ISSUE THREAD

**Issue by thytetgc** [alseambusher/crontab-ui#103]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node?
- [x] The `node_modules` folder has right permissions 
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

I did not understand.

Where and how should I put

BASIC_AUTH_USER = user BASIC_AUTH_PWD = SecretPassword

**Comment by alseambusher** [comment]
You need to make it environment variables. Two ways you can do it:

1. Exporting before starting crontab-ui
```bash
export BASIC_AUTH_USER=user
export BASIC_AUTH_PWD=SecretPassword
crontab-ui
```
2. Adding before crontab-ui in the command
```bash
BASIC_AUTH_USER=user BASIC_AUTH_PWD=SecretPassword crontab-ui
```
