### ISSUE TITLE
A little bit of advice!

### ISSUE THREAD

**Issue by ztj1993** [alseambusher/crontab-ui#108]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

The software is very well written, but there are several suggestions.

> Try not to modify system files

Especially /var/spool/ cron file and write /etc/crontabs file, all of which should not be modified

> Error logs let users define

Error logs can simply define a directory for users to write, monitor file changes, send mail or send hooks. They can also define log interval symbols.

> The procedure is as simple as possible

The command MD5 can be used to identify each command and mark the name corresponding to it.

---

The above is from program translation.

**Comment by alseambusher** [comment]
Thanks for the advice. You can find logs folder like this `$(npm root -g)/crontab-ui/crontabs/logs `
