### ISSUE TITLE
Unexpected identifier in /crontab-ui/views/index.ejs

### ISSUE THREAD

**Issue by starbuck93** [alseambusher/crontab-ui#109]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
`node -v v13.2.0`  `npm --version 6.13.1`
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
```
drwxr-xr-x 10 1001 1001 4096 Nov 24 09:15 /usr/local/lib/nodejs/node-v13.2.0-linux-armv7l/lib/node_modules/crontab-ui
```
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

System: Raspberry Pi 2 B+, image: `2019-09-26-raspbian-buster-lite`
```
Linux hostname 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```

Installed crontab-ui from `npm` first, got this error message in the browser, then went back and installed via building a docker image and got the same error message in the browser:

```
{"message":"Unexpected identifier in /crontab-ui/views/index.ejs while compiling ejs\n\nIf the above error is not helpful, you may want to try EJS-Lint:\nhttps://github.com/RyanZim/EJS-Lint\nOr, if you meant to create an async function, pass `async: true` as an option."}
```

**Comment by Vash1990** [comment]
Got the same issue on an Ubuntu 18.04 with:  `node -v v13.2.0` `npm --version 6.13.1`

**Comment by alseambusher** [comment]
Interesting. I can't reproduce this on mac. What happens when you run this:

```
docker run -p 8000:8000 alseambusher/crontab-ui
```

**Comment by starbuck93** [comment]
@alseambusher The error message I pasted above is what happens. I installed it via `npm` then created a docker container and both had the same result.

**Comment by arimav** [comment]
Same error here. It was running fine on macOS 10.12 and then I upgraded to 10.15 and it was not behaving properly so I updated npm and crontab-ui to the latest version ran the command and same error.

{"message":"Unexpected identifier in /usr/local/lib/node_modules/crontab-ui/views/index.ejs while compiling ejs\n\nIf the above error is not helpful, you may want to try EJS-Lint:\nhttps://github.com/RyanZim/EJS-Lint\nOr, if you meant to create an async function, pass `async: true` as an option."}

**Comment by alseambusher** [comment]
I am suspecting it might have to do with permissions. Can you run this and tell me what you get?
```
ls -lR $(npm root -g)/crontab-ui/ 
```

Also, check if `sudo crontab-ui` works by any chance?

**Comment by alseambusher** [comment]
Might be related to https://github.com/mde/ejs/issues/477

**Comment by alseambusher** [comment]
Upgrade to 0.3.9 (latest) https://github.com/alseambusher/crontab-ui/releases/tag/v0.3.9

**Comment by arimav** [comment]
Yup, it worked!!!

Now if I can only figure out where my backups are stored :(

Thanks

**Comment by alseambusher** [comment]
Great!

It is usually stored in `$(npm root -g)/crontab-ui/crontabs`  folder. Ideally, you should copy the contents of that folder when you upgrade crontab-ui. I should add that to readme.
