### ISSUE TITLE
Dockerization time, add agent would be good for me!

### ISSUE THREAD

**Issue by kuituoshi** [alseambusher/crontab-ui#112]
# This is not an issue

* Cause many people is using docker,  Are you planning to dev agent ?
* What agent means ? Crontab-UI just be made for a controller, all agent are deployed in different docker host, Crontab-UI controll which agent node the jobs run in , it's called distributed mode
* Can you do this ?  I am from china , happy to chat here

**Comment by JeremyMahieu** [comment]
The use of having cron in a docker is very limited. I would also like to be able to use this UI to configure cron of the docker host or other docker containers.
