### ISSUE TITLE
 Operation failed: Internal Server Error. Please see error log for details.

### ISSUE THREAD

**Issue by ppapadeas** [alseambusher/crontab-ui#113]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

I am getting 
```
Operation failed: Internal Server Error. Please see error log for details.
```
while trying to "Save to Crontab". Where do I see the log?

**Comment by alseambusher** [comment]
Logs have been enabled in https://github.com/alseambusher/crontab-ui/commit/970e461621e6906ce7259b9dfcacbff90dae858b

**Comment by benjaminv** [comment]
I run to the same error if i am trying to use crontab-ui as a non-root user. 

/home/ubuntu# [Error: EACCES: permission denied, open '/tmp/crontab']
 {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/tmp/crontab'
}
[Error: EACCES: permission denied, open '/tmp/crontab'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/tmp/crontab'
}

**Comment by ivsanro1** [comment]
@benjaminv I solved it by doing `sudo chmod 666 /tmp/crontab`
