### ISSUE TITLE
Use docker in a subfolder

### ISSUE THREAD

**Issue by andrewgamez** [alseambusher/crontab-ui#115]
Any way to use crontab-ui with docker in a subfolder?

**Comment by alseambusher** [comment]
What do you mean by subfolder?

**Comment by andrewgamez** [comment]
In a non-root folder, domain.com/folder/crontab-ui/

**Comment by DarkAxi0m** [comment]
I don't know if @andrewgamez  is using [Traefix ](https://docs.traefik.io/) but with my setup i am using the rule.   `Host(`example.com`) && PathPrefix(`/crontab`)`

So the site lives at https://example.com/crontab

Basic Auth works, but after there is just a blank page.  There is nothing in the logs from what i can see.

**Comment by alseambusher** [comment]
Yes. You can set the env variable `BASE_URL` Eg:
```
BASE_URL="/folder/crontab-ui/" crontab-ui
```
Will start the service at `http://127.0.0.1:8000/folder/crontab-ui`. You can also use `HOST` and `PORT`
