### ISSUE TITLE
Cannot get crontab-ui to execute any command

### ISSUE THREAD

**Issue by donnib** [alseambusher/crontab-ui#119]
I am installing crontab-ui in a docker container using the official image. It runs, i can get to the web ui. i make a new entry for example ping google.com and try run but nothing happens, no logs, no errors, the container logs shows nothing so i don't know what's happening. 

What am i doing wrong ?

**Comment by FickleLife** [comment]
I have the same issue, not sure what we are missing from docker config...

**Comment by Moekr** [comment]
Did you click the "Save to crontab" button?

**Comment by phith0n** [comment]
I have the same issue. After restart the container, it works, I don't know why.

**Comment by phith0n** [comment]
> I have the same issue. After restarting the container, it works, I don't know why.
> 
> So, if I added a new job, a restart is needed.

After deep testing, I found that when I add a job1 then click the "save to crontab", the file is written at /etc/crontabs/root, but nothing is done. After restarting the container or add a job2, the job1 is starting running.

**Comment by YouveGotMeowxy** [comment]
@FickleLife 

Did you ever figure this out? I'm trying to run the docker container on a Pi (https://hub.docker.com/r/donaldrich/crontab-ui) and nothing seems to be happening?


After adding a new cron job, clicking "Save to crontab", and restarting the container, then trying to run it, I get nothing apparent happening.

when I try to check if the crontab file was edited, I get this:

```
$ crontab -l
no crontab for pi
$ sudo crontab -l -u root
no crontab for root
```

**Comment by alseambusher** [comment]
This should be fixed in https://github.com/alseambusher/crontab-ui/commit/42e677d8d26d11dfc0ade2fade80fbca8c120fd5 

Please re-test this by pulling the latest (or 0.3.12) image https://hub.docker.com/repository/docker/alseambusher/crontab-ui/tags

**Comment by alseambusher** [comment]
I am closing this issue. Please re-open if it still persists.
