### ISSUE TITLE
Simple REST API for adding new cronjobs

### ISSUE THREAD

**Issue by anx-mwutte** [alseambusher/crontab-ui#122]
Hi, it would be nice to have a simple REST API for adding new cronjobs.

For authentication a simple configurable token (and an optional IP for accessing the API) would be enough.

Kind regards

**Comment by alseambusher** [comment]
This is technically possible. Although I don't have it documented, with some digging it should be possible to do it. 
All the available end points. https://github.com/alseambusher/crontab-ui/blob/master/routes.js
GET/POST parameters etc: https://github.com/alseambusher/crontab-ui/blob/master/app.js

**Comment by alseambusher** [comment]
Eg:
Start crontab-ui like this:
```bash
BASIC_AUTH_USER=user BASIC_AUTH_PWD=SecretPassword crontab-ui
```

Then you can use curl:
```bash
 curl -u user:SecretPassword -XGET 'localhost:8000/export'
```

The response should be like this:
```
{"name":"ls","command":"ls","schedule":"* * * * *","stopped":false,"timestamp":"Tue Nov 26 2019 22:38:51 GMT-0800 (Pacific Standard Time)","logging":"true","mailing":{},"created":1574836731807,"_id":"ZVynPMql5JzwqATR"}
{"name":"ping","command":"ping google.com","schedule":"*/1 * * * *","stopped":false,"timestamp":"Tue Nov 26 2019 22:24:37 GMT-0800 (Pacific Standard Time)","logging":"true","mailing":{},"created":1574835877331,"_id":"o9cMoYqpzwBM5QqC"}
```
