### ISSUE TITLE
Impossible install in raspberry

### ISSUE THREAD

**Issue by RobertusIT** [alseambusher/crontab-ui#123]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [X ] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [X] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [X] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [X] Gone through existing open and closed issues. 

Hi,
on my raspberry is impossible install it.

I lost 2 days without success.

> pi@raspberrypi:~$ wget https://nodejs.org/dist/v14.2.0/node-v14.2.0-linux-armv7l.tar.gz
> tar -xzf node-v14.2.0-linux-armv7l.tar.gz 
> sudo mv node-v14.2.0-linux-armv7l /opt/node
> sudo apt-get purge nodejs
> echo 'export PATH=$PATH:/opt/node/bin' > ~/.bashrc
> source ~/.bashrc
> npm install -g crontab-ui
> and i have:
> pi@raspberrypi:~$ npm install -g crontab-ui
> /opt/node/bin/crontab-ui -> /opt/node/lib/node_modules/crontab-ui/bin/crontab-ui.js
> /opt/node/bin/crontab-ui-mailer -> /opt/node/lib/node_modules/crontab-ui/bin/crontab-ui-mailer.js
> npm WARN notsup Unsupported engine for crontab-ui@0.3.9: wanted: {"node":"latest"} (current: {"node":"14.2.0","npm":"6.14.4"})
> npm WARN notsup Not compatible with your version of node/npm: crontab-ui@0.3.9
> 
> + crontab-ui@0.3.9
> updated 1 package in 9.878s

Please i didn't figure out.

I wish to have crontab-ui on my raspberry and that crontab-ui, come up automatically when reboot.
So i can add or remove cron, from my another pc in lan, not outside lan, so nginx not needed.

Simple, but i tried a lot of tutorial without success.

I hope that someone, can help me to do this a simple thing.

**Comment by alseambusher** [comment]
From the logs you have posted, it looks like it is just a warning and it is installing it. Do you face any issue while starting it?

**Comment by alseambusher** [comment]
If you wish to have crontab-ui run on startup you may have to use systemd or rc.d methods depending on the OS you have installed.

**Comment by adibacco** [comment]
I got same warning and the crontab-ui is continuosly restarting (raspberry buster, node 14.4.0)

**Comment by minecraftchest1** [comment]
It is working fine for me.
