### ISSUE TITLE
Feature request: is it possible to deploy across multiple server nodes?

### ISSUE THREAD

**Issue by Zhenye-Na** [alseambusher/crontab-ui#124]
Hi @alseambusher ,

thank you for creating this project, it is very handy and I am interested in importing this tool for our internal usage. Before doing that I am wondering if this project can be deployed across multiple server nodes, to be explicitly, they are AWS EC2 nodes.

If not, will you put it in the "future goal", I of course would love to contribute to this feature if possible.

I would love to hear your feedback concerning this feature.

Thank you so much!

Best,
Zion

**Comment by alseambusher** [comment]
Hi @Zhenye-Na,
Yep it should be possible and will be like deploying any nodejs application.
Ref: https://github.com/alseambusher/crontab-ui/blob/master/README/nginx.md

I will close this for now. Feel free to re-open it if you face any issues.
