### ISSUE TITLE
Error deleting backup snapshots.

### ISSUE THREAD

**Issue by renatoaraujoc** [alseambusher/crontab-ui#125]
Hi, I've just started using your app and I'm having issues deleting a backup, I attached a screenshot.

- Running Node v12.18
- Running Crontab-UI latest version from "npm install -g crontab-ui" as of today.
![Captura de Tela 2020-06-05 às 17 32 39](https://user-images.githubusercontent.com/358128/83920438-9825ea80-a752-11ea-9b2f-aad1d874261f.png)

This shows up when deleting a backup:
![Captura de Tela 2020-06-05 às 17 15 26](https://user-images.githubusercontent.com/358128/83919992-31a0cc80-a752-11ea-9317-83464dbadcfc.png)

**Comment by alseambusher** [comment]
It should be fixed in this commit https://github.com/alseambusher/crontab-ui/commit/08360cd91bbac9487df33d72e2057ec3e423deb0

Please retest with v0.3.10

**Comment by renatoaraujoc** [comment]
Hey @alseambusher, it's working again but upon doing `npm install -g crontab-ui` I lost all my backups, is there a way to update the app without losing data?

Thanks!
