### ISSUE TITLE
Suggestion: Add Option to hide "Get from crontab" button

### ISSUE THREAD

**Issue by MutedJam** [alseambusher/crontab-ui#127]
I am just trying out crontab UI and it is a really nice tool to let multiple users easily set up and manage cron jobs on a shared machine in our office. Thank you so much for that!

However, the "Get from crontab" button seems to re-import add existing crontab entries, leading to potential duplicates with no undo option. So I am wondering if an option to hide this button could be added, maybe through an environmental variable. This could prevent painful accidents.

**Comment by alseambusher** [comment]
I would recommend taking a backup whenever you use that feature as like you pointed out, can potentially cause painful accidents:

![image](https://user-images.githubusercontent.com/1242542/87158983-31aa6400-c2de-11ea-9cc8-736326ae5dab.png)
