### ISSUE TITLE
Docker Crontab UI - Edit the host crontab

### ISSUE THREAD

**Issue by TaylorDale** [alseambusher/crontab-ui#128]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [ x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [ x] Gone through existing open and closed issues. 

I'm trying to run this dockerized to edit the host's crontab file, but I can't read anywhere in the documentation that mentions this. Running it by itself edits the docker's crontab file, which is not useful, and if I try volume mounting my host crontab file 

`docker run -d -p 8000:8000 -v /etc/cron.d/jobs:/etc/crontabs/root alseambusher/crontab-ui`

It actually does work to some extent (writes job to the file), however the web interface reports an HTTP 500 error. Is this the right way to do it?

**Comment by CountParadox** [comment]
also interested, were you able to make any progress on this @TaylorDale ?

**Comment by back-2-95** [comment]
Maybe the docker run command needs better privileges https://docs.docker.com/engine/reference/commandline/run/#full-container-capabilities---privileged

**Comment by svh1985** [comment]
Also interested, running Ubuntu Server 20.04

**Comment by alseambusher** [comment]
@TaylorDale interesting use case 🥇. I tried what you did and found that it gives the following error (check browser console):
``` 
{
message: "Command failed: crontab /etc/crontabs/root crontab: can't move 'root.new' to 'root': Resource busy "
}
```
Meaning, docker is keeping the file busy while `root.new` file is being moved to `root` file. It should still work like you pointed out but I would recommend mounting the entire path instead of just the file:
``` bash
docker run -d -p 8000:8000 -v /etc/cron.d:/etc/crontabs alseambusher/crontab-ui
```

**Comment by TaylorDale** [comment]
To be honest I assumed that this would be the docker versions sole purpose but I guess not! 

Thanks for the info on that one I'll give it a go.

**Comment by joselito11** [comment]
I can get it working on docker. The cron job does not work and not appear in crontab. Should I use this folder path: `docker run -d -p 8000:8000 -v /etc/cron.d:/etc/crontabs alseambusher/crontab-ui`?

**Comment by YouveGotMeowxy** [comment]
@alseambusher 

No luck for me. I tried this:

```
sudo docker run --name crontab-ui -v pi_crontabui_data:/crontab-ui/crontabs/ -v '/etc/cron.d:/etc/crontabs' -v /etc/localtime:/etc/localtime:ro -e BASIC_AUTH_USER=pi -e BASIC_AUTH_PWD=stuff -d -p 8000:8000 donaldrich/crontab-ui:latest
```

Then I did a "get from crontab", backed it up, then did a "save to crontab". Finally, "run now":

`apt-get update && sudo apt-get upgrade -y`

And the error log shows:

> Wed Jan 20 22:36:19 CST 2021
/bin/sh: apt-get: not found

I'm wondering the same as @TaylorDale , what is the point of having it in a docker container if it can't control the crontab on the host? I canty think of a reason to want to run any cron jobs inside the container itself?

**Comment by MarvinJWendt** [comment]
If someone is still looking for this, like me, this docker-compose.yml works fine to run cron jobs on the host:

```yml
version: '3.3'
services:
    crontab-ui:
        image: alseambusher/crontab-ui
        volumes:
            - /etc/cron.d:/etc/crontabs # I am not sure if this mount is needed
            - ./data:/crontab-ui/crontabs/
            - /var/spool/cron/crontabs:/var/spool/cron/crontabs
```

@alseambusher maybe this can be added to docs?

**Comment by Macleykun** [comment]
So, does the docker variant of this project run commands on the host or in the container..?

**Comment by alseambusher** [comment]
@Macleykun it can do both. If you are looking to run commands on the host, you can follow the last section here https://github.com/alseambusher/crontab-ui#docker

**Comment by Macleykun** [comment]
> @Macleykun it can do both. If you are looking to run commands on the host, you can follow the last section here https://github.com/alseambusher/crontab-ui#docker

oooh awsome! thanks for the info <3 !
Btw, wouldn't it be handier by default to recommend mounting the crontab to the host? I would think that if i accidentally remove the container, that all my settings would be lost :o !

I did see:
`docker run -d -p 8000:8000 -v /etc/cron.d:/etc/crontabs alseambusher/crontab-ui`
which is think is perfect for me! But wanted to suggest that to be maybe the recommended way, as inexperienced users could maybe lose their stuff if they aren't careful.
