### ISSUE TITLE
docs: link is boken

### ISSUE THREAD

**Issue by crazyx13th** [alseambusher/crontab-ui#129]
small issue, "this" is broken :-)
![grafik](https://user-images.githubusercontent.com/8912561/87658869-0a7be880-c75d-11ea-83f6-516c1fa53866.png)

**Comment by crazyx13th** [comment]
same here: ![grafik](https://user-images.githubusercontent.com/8912561/87659539-03090f00-c75e-11ea-981d-7d8e3979f8c0.png)

**Comment by alseambusher** [comment]
Fixed https://github.com/alseambusher/crontab-ui/commit/593f6321e480daa06336db841f77bf4fdb63b13d :)
