### ISSUE TITLE
Log commands and use Environment Variables when using running commands manually

### ISSUE THREAD

**Issue by AndreiArdelean1** [alseambusher/crontab-ui#137]
When running a command manually from the UI it is not logged to file, only to `crontab-ui` stdout. Also, the Environment Variables are not passed to the command.

**Comment by tuxuday5** [comment]
You mean 'Run Now'? This doesn't seem to use cron. That's why its not logging to any files. 
If you want in logs, have to do it explicitly.

**Comment by AndreiArdelean1** [comment]
Yes, 'run now' doesn't use crontab, but even so, it should use the environment variables and should log the output otherwise the crontab and the 'run now' would have different behaviors.

**Comment by tuxuday5** [comment]
Agree with environment vars. For o/p you can do the re-direction by yourself and check.

**Comment by tuxuday5** [comment]
Ignore. See that you had modified per your requirement and raised a PR.

**Comment by alseambusher** [comment]
I have merged this https://github.com/alseambusher/crontab-ui/pull/138
