### ISSUE TITLE
Get from crontab does not load crons with = in command

### ISSUE THREAD

**Issue by ryanMeredith** [alseambusher/crontab-ui#141]
After clicking Get from Crontab it only gets crons without =

for example this cron is not loaded
19 4 * * * curl -L "https://www.XXXX.com/sitemaps.php?showMap=XXXX"

However all other crons are loaded

Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x ] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x ] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x ] Gone through existing open and closed issues.

**Comment by ryanMeredith** [comment]
My mistake it is not the ? it is the = sign

**Comment by samcro1967** [comment]
I believe the same is true for | (pipe) as well.
