### ISSUE TITLE
Full URL on terminal

### ISSUE THREAD

**Issue by robsonsobral** [alseambusher/crontab-ui#15]
Hi!

I just discovered your app. Thank you for coding it.

May I suggest you something? [Hugo](http://gohugo.io) shows a link in terminal, which can be clicked. I'm not sure how this works, but I **guess** it's just a matter of using a full url.

Can you, please, try to add the protocol to the URL on terminal? Instead of `localhost:8000`, `http://localhost:8000`.

Thank you!

**Comment by alseambusher** [comment]
Hi,
You have to modify this line https://github.com/alseambusher/crontab-ui/blob/master/app.js#L149
Would you like to contribute to the project by forking it and making that change? :)

Thanks

**Comment by robsonsobral** [comment]
Sure! I don't have the expertise to test it, but I can try!
