### ISSUE TITLE
Swap out the current shell for something useful 

### ISSUE THREAD

**Issue by timdonovanuk** [alseambusher/crontab-ui#151]
Been trying to love this, but half the commands I write and test in a normal bash shell don't translate to this, since it uses /bin/sh. This means even your standard awk, find, tar, curl etc. function differently or are missing a bunch of stuff. Very frustrating! 

Other than that, its awesome, thank you!

**Comment by alseambusher** [comment]
I think you should be able to switch to any shell bu setting the `SHELL` env variable.

![Screen Shot 2021-06-28 at 11 20 02 AM](https://user-images.githubusercontent.com/1242542/123684819-ca453700-d802-11eb-948e-5a4895c0f9bf.png)
