### ISSUE TITLE
It won't install on latest node v15.11.0 + npm v7.6.0

### ISSUE THREAD

**Issue by benjaminv** [alseambusher/crontab-ui#152]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [y] Running latest npm and node? -  node: 'v15.11.0', npm: '7.6.0'
- [y] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`) - drwxrwxr-x
- [y] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [y] Gone through existing open and closed issues. 

```
~$ npm install crontab-ui
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'crontab-ui@0.3.13',
npm WARN EBADENGINE   required: { node: 'latest' },
npm WARN EBADENGINE   current: { node: 'v15.11.0', npm: '7.6.0' }
npm WARN EBADENGINE }
```
And it simply does not install or run.
It however does create and copy over file under `~/.npm-global/lib/node_modules/crontab-ui`

Please help or fix.

**Comment by benjaminv** [comment]
As far as I can try, the version of {node: 'v15.8.0', npm: '7.5.1' } for some reason still works.

**Comment by alseambusher** [comment]
I think this is just a warning right. Does it not work?
Anyway I will change the min version to a lower value. Thanks!
