### ISSUE TITLE
Private Disclosure

### ISSUE THREAD

**Issue by omriinbar** [alseambusher/crontab-ui#158]
Hey,
Do you have an email for private disclosure?

**Comment by PascalNoisette** [comment]
Hi ! 

I am not a core commiter but I was maintaining and running a fork for quite some time, I am also in the process of making a [complete refactoring based on NextJs with react](https://github.com/GenghisTask/Workspace), it would be nice to know if the new approch will avert the problem or not.

Could you [email](mailto:netpascal0123@aol.com) me the details too ? 

Thanks,
Pascal Noisette

**Comment by omriinbar** [comment]
Hey @PascalNoisette, unfortunately don't think that that would be responsible. However I will ask If I can send it to you once I manage to contact them :) If not than you will be able to see it once they fix the issue.

**Comment by alseambusher** [comment]
@omriinbar pardon my ignorance, what does that mean?
