### ISSUE TITLE
can support nodejs version 14.x?

### ISSUE THREAD

**Issue by msccreater** [alseambusher/crontab-ui#165]
can support nodejs version 14.x?
now it's only support node version latest , can you support node version 14.x, thks

**Comment by grigio** [comment]
What do you mean ?
it's working with latest stable node v14.17.5

**Comment by msccreater** [comment]
> What do you mean ?
> it's working with latest stable node v14.17.5

i install in termux, my node version is v14.15.4
when i run crontab-ui, nothing page in browser https:/127.0.0.1:8000
