### ISSUE TITLE
Validation alerts

### ISSUE THREAD

**Issue by robsonsobral** [alseambusher/crontab-ui#17]
Hi!

I download your app because my cronjobs never, ever worked. Never. Using it, I realize the reason: simple quotes. After try to set a job, crontab-ui permanently crashed. I had to uninstall and reinstall it.

Maybe this should be 2 issues:

- to prevent the app from crashing when reading bad cron jobs;
- form validation rules to prevent bad jobs;

Does it seen reasonable?

**Comment by alseambusher** [comment]
Can you give an example of the bad job that you were able to setup?

**Comment by robsonsobral** [comment]
Sure!

Note the `0` instead of `O`:

```shell
wget -q0- "http://domain.com.br?foo=bar" &> /dev/null 2>&1`
```

Note the `"` instead of `'`:

```shell
rsync -avz --exclude '*/cache/*' --exclude '*/captchas/*' -e "ssh" user@xxx.xxx.xxx.xx:/var/www/domain.com/ /home/user/_backup/domain.com
```

Dumb, right?

**Comment by robsonsobral** [comment]
The first case needs something hard, like [ExplainShell](https://github.com/idank/explainshell).

Maybe the second one is less harder.
