### ISSUE TITLE
After container restart, cron job only resumes after clicking 'save to crontab'

### ISSUE THREAD

**Issue by holygekko** [alseambusher/crontab-ui#173]
I'm running the alseambusher/crontab-ui:latest image. 

After restarting the container and opening the UI, I can see the jobs I've added and the icon (glyphicon-floppy-saved) indicates they're saved to crontab. However it doesn't run.

When I click the 'Save to crontab' button it starts running.

Is it possible to automatically resume running the previously 'saved to contab' jobs after restarting the container?

**Comment by holygekko** [comment]
Ah I see I need to use the --autosave flag (issue: https://github.com/alseambusher/crontab-ui/issues/29), but how do I do this with the docker image?

**Comment by holygekko** [comment]
Is this only possible by forking the project, adjusting supervisord.conf (adding --autosave to line 10) and building a new image?

**Comment by alseambusher** [comment]
@holygekko Yes. Thats the only way as of now.
