### ISSUE TITLE
process.env.HUMANCRON error

### ISSUE THREAD

**Issue by Sanjeev3008** [alseambusher/crontab-ui#196]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues.

**Comment by Sanjeev3008** [comment]
var humanCronLocate = process.env.HUMANCRON ?? "en"
                                             ^
SyntaxError: Unexpected token ?

Did not get the error in local but when i run it a gateway server, the application doesnt start

**Comment by alseambusher** [comment]
Duplicate https://github.com/alseambusher/crontab-ui/issues/204
