### ISSUE TITLE
Error: Expression has only 1 part. At least 5 parts are required.`

### ISSUE THREAD

**Issue by gabrielmaster123** [alseambusher/crontab-ui#198]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 
 When I try to run my job manually I get this error

`Running job
ID: 30jwU1hIYBDzNHRG
Original command: python '/home/gabriel/Documents/anisync/plexanisync/PlexAniSync.py'
Executed command: ((({ python '/home/gabriel/Documents/anisync/plexanisync/PlexAniSync.py'; } | tee /tmp/30jwU1hIYBDzNHRG.stdout) 3>&1 1>&2 2>&3 | tee /tmp/30jwU1hIYBDzNHRG.stderr) 3>&1 1>&2 2>&3); if test -f /tmp/30jwU1hIYBDzNHRG.stderr; then date >> "/usr/local/lib/node_modules/crontab-ui/crontabs/logs/30jwU1hIYBDzNHRG.log"; cat /tmp/30jwU1hIYBDzNHRG.stderr >> "/usr/local/lib/node_modules/crontab-ui/crontabs/logs/30jwU1hIYBDzNHRG.log"; fi; if test -f /tmp/30jwU1hIYBDzNHRG.stdout; then date >> "/usr/local/lib/node_modules/crontab-ui/crontabs/logs/30jwU1hIYBDzNHRG.stdout.log"; cat /tmp/30jwU1hIYBDzNHRG.stdout >> "/usr/local/lib/node_modules/crontab-ui/crontabs/logs/30jwU1hIYBDzNHRG.stdout.log"; fi
Error: Expression has only 1 part. At least 5 parts are required.`

i have set this to run hourly

**Comment by Victorhtf** [comment]
I'm also with this error, dont know why. That doesnt make sense.

**Comment by cparello** [comment]
when you use the @hourly i get the error but if i replace it with a standard cron expression 0 * * * * the errs goes away 1 part vs 5 parts

**Comment by LunarTwilight** [comment]
> when you use the @hourly i get the error but if i replace it with a standard cron expression 0 * * * * the errs goes away 1 part vs 5 parts

Oh that's a good catch, I didn't pick up on that being the reason for the error. Also your message gave me idea to poke around crontab-ui's code and see what's causing the error and it looks like a library that crontab-ui uses (construe) doesn't support crontab extensions (https://github.com/bradymholt/cRonstrue/issues/190, https://github.com/bradymholt/cRonstrue/issues/277)
![image](https://github.com/alseambusher/crontab-ui/assets/13520392/1e174d3e-6e7f-4753-aaa4-f88f46ebd6b8)
