### ISSUE TITLE
Can't run bash scripts.

### ISSUE THREAD

**Issue by opentree27** [alseambusher/crontab-ui#205]
Trying to run a bash script but keep getting /bin/sh: "path to script": not found.
I am running in a docker container on truenas scale. I have tried setting the environment variable SHELL to /bin/bash in gui and cli and on the WebUI as mentioned in #151 but I still get the same error. Any known ways to fix this?

Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues.

**Comment by alseambusher** [comment]
That probably means that crontab is not able to find the script and not related to the shell as such. Can you try giving absolute path?
