### ISSUE TITLE
Cron job hangs because of 3>&1 1>&2 2>&3 in the command wrapping

### ISSUE THREAD

**Issue by outfoxer** [alseambusher/crontab-ui#212]
Hi!

I'm running **alseambusher/crontab-ui:0.3.16** in Docker.

For some reason this swapping `3>&1 1>&2 2>&3` in the command wrapping makes the process to hand and never exits. So I get a lot of zombie processes after many jobs runs.

How can this be fixed?

**Comment by alseambusher** [comment]
Can you give a minimal example from crontab.db?
