### ISSUE TITLE
Is it possible to run crontab-ui inside a docker container and be accessible from anywhere in network?

### ISSUE THREAD

**Issue by Jeff534** [alseambusher/crontab-ui#218]
I tried the following command, however it complained the host and port number not accessible. 
HOST=[VM PUBLIC IP] PORT=9000 crontab-ui

I also mapped the port in docker compose file with no luck:
ports:
      - "9000:9000"

Crontab-ui works in VM level, but I'm wondering if I can move it to a docker container.

Thanks!

Jeff

**Comment by TruckerZer0** [comment]
I believe you need to map it to '0.0.0.0:hostport:containerport', in your case 0.0.0.0:9000:9000, where 0.0.0.0 stands for "listen on all network interfaces, not just the docker host machine's internal network; At least that's how I made it work. Cheers!
