### ISSUE TITLE
crontab-ui service does not start

### ISSUE THREAD

**Issue by BrandonsAccount** [alseambusher/crontab-ui#23]
Uninstalled and reinstalled using `npm install -g crontab-ui` multiple times and am not able to get the service to start when executing `crontab-ui`. I do not receive an error and do not know where to search for logs. Using Ubuntu 14.04 LTS.

**Comment by alseambusher** [comment]
Hi,

This seems like a permission issue. Please refer [this](https://docs.npmjs.com/getting-started/fixing-npm-permissions) to set permission for node_modules and try again.

**Comment by BrandonsAccount** [comment]
Thanks Suresh. I tried option #1 and option #2 with no luck. Tried uninstalling and reinstalling again as well.

-Brandon

**Comment by alseambusher** [comment]
Let me know if it works if you try `sudo crontab-ui`

**Comment by BrandonsAccount** [comment]
Thanks Suresh. I have tried that multiple times throughout my troubleshooting with no success. I’ve also tried sudo PORT=9000 crontab-ui.

-Brandon

**Comment by alseambusher** [comment]
- try deleting your `crontab-ui` folder in your root `node_modules` folder
- see if you have the latest node and npm

**Comment by BrandonsAccount** [comment]
I executed the following with no success.

sudo npm uninstall –g crontab-ui
/home/brandon/.npm-global/rm -r crontab-ui
sudo npm install –g npm
sudo npm install –g crontab-ui

-Brandon

**Comment by jargot** [comment]
@BrandonsAccount Had the same issue, turned out to be an faulty (probably out of date) version of node.

I uninstalled everything, then re-installed node as [per the official instructions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) then reinstalled crontab-ui and it works with sudo now :)

Good luck
