### ISSUE TITLE
Can't  run docker commands inside the container

### ISSUE THREAD

**Issue by leander530** [alseambusher/crontab-ui#237]
Hi，
 I deployed with the docker image, it can't  run docker commands inside the container， Even if already used below parameters to run the docker：
`-v /var/run/docker.sock:/var/run/docker.sock \`
`-v /usr/bin/docker:/usr/bin/docker \`

The error says ‘/bin/ash: docker: not found’， Is there any way to solve it?

**Comment by PovilasID** [comment]
It's because docker CLI is not installed on the container you can do it yourself by entering the container and adding it or I made a fork that includes it.
https://github.com/PovilasID/crontab-ui-docker
