### ISSUE TITLE
primary crontab erased after installing and using crontab-ui on QNAP QTS

### ISSUE THREAD

**Issue by Arnaud1110** [alseambusher/crontab-ui#253]
Hello all,
I don't know if someone can help, but I'm attempting.

I tried to install and use crontab-ui (CrontabUI_0.3.16_arm_64.qpkg) on my nas qnap (qts 5.1.8). For installing in the qts App Center, I use an administrator account MyName (not the admin account which is desactivated). On the surface in the interface it looks good : I can create et run some tests jobs.

BUT

- using this crontabui tool allows the creation of scheduled tasks, but by ... overwriting the contents of the system crontab (all standard tasks have disappeared)! So, after creating 2 jobs, the crontab of the user MyName contains only these 2 jobs (and all the standard jobs have disappeared).
- and when the system is restarted, the system crontab is back in place (so the crontab of the user MyName contains the standard jobs), but the tasks generated by the crontabui tool have disappeared...

What did I do wrong in this case? And How could I resolve this issue?
Thank you for any idea...
Arnaud

**Comment by OneCDOnly** [comment]
Hi @Arnaud1110  🤓 

This is something you'll need to raise with the package maintainer (Qoolbox aka QNAP_Stephane). He will need to adjust the installation parameters for this package. You can do this through the [myqnap.org repo](https://www.myqnap.org/product/crontabui/), or on the [QNAP Community forum](https://forum.qnap.com).

**Comment by Arnaud1110** [comment]
Hi @OneCDOnly 
Ok thank you for your advice.
Arnaud
