### ISSUE TITLE
Replace nginx, lighttpd for auth ?

### ISSUE THREAD

**Issue by Jufo84** [alseambusher/crontab-ui#27]
Back to the topic:
https://github.com/alseambusher/crontab-ui/blob/master/README/nginx.md#authentication
How to replace recommended nginx, lighttpd on Raspberry PI ?

P.S. Would have been nice if crontab-ui had a built-in login

Best Regards
Robert

**Comment by alseambusher** [comment]
Shouldn't be much different from that link. And it would depend on the OS you are running on Pi.

We intentionally didn't build login as it would be a major task to keep up with the standards. Other authentication methods work well and are safe to use.

Thanks
