### ISSUE TITLE
Feature suggestion "Run now"

### ISSUE THREAD

**Issue by vbauer** [alseambusher/crontab-ui#37]
Is it possible to add something like "Run now" to force command execution?

**Comment by phrozendice** [comment]
This would be GREAT!

**Comment by sean29** [comment]
+1

**Comment by abonstu** [comment]
+1

**Comment by firestalk** [comment]
+1

**Comment by alseambusher** [comment]
Available in the latest release:

https://github.com/alseambusher/crontab-ui/releases/tag/v0.3.5
