### ISSUE TITLE
Safari ReferenceError: Can't find variable: newJob

### ISSUE THREAD

**Issue by VVZen** [alseambusher/crontab-ui#38]
_macOS El Capitan 10.11.6, npm 4.0.5, node 6.9.4, **Safari 9.1.2 (11601.7.7)**_

When clicking on a new job on Safari, the following errors occur:

```
SyntaxError: Unexpected identifier 'name'
(anonymous function) script.js:114

ReferenceError: Can't find variable: newJob
onclick localhost:62
```

In Chrome it works without problems.
Great app, by the way!

**Comment by alseambusher** [comment]
Unable to replicate in Safari 10.0.3
