### ISSUE TITLE
Apache2 reverse proxy not working

### ISSUE THREAD

**Issue by Simonell** [alseambusher/crontab-ui#40]
Please change resources loading, because apache2 reverse proxy in /crontab tryin to load jquery and bootstrap from root domain.

**Comment by vendor-vandor** [comment]
Save scripts to crontab-ui/public/js

**Comment by gildo** [comment]
Same for nginx

**Comment by obissick** [comment]
I got it working with pm2 and nginx.

**Comment by buddy-ekb** [comment]
There is pull request #70 which hopefully solves the case.

**Comment by larrybahr** [comment]
Any plans to make paths relative?

**Comment by youngjuning** [comment]
any update?

**Comment by alseambusher** [comment]
Thanks @buddy-ekb 

You can test it out with this release https://github.com/alseambusher/crontab-ui/releases/tag/v0.3.11

I will close this. Feel free to re-open it if it is still not working.
