### ISSUE TITLE
Block Scoped Declarations outside strict mode

### ISSUE THREAD

**Issue by russlamb** [alseambusher/crontab-ui#42]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [X] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [X] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [X] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [X] Gone through existing open and closed issues. 

You don't specify what version of node is compatible above.  I'm running v7.6.  

When i run crontab-ui I get the following error.  What could cause this?

---------

/usr/local/lib/node_modules/crontab-ui/app.js:200
    let crontabdb = __dirname + "/crontabs/crontab.db";
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/crontab-ui/bin/crontab-ui.js:3:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by alseambusher** [comment]
Hi,

Which OS are you using and did you install crontab-ui through npm?

**Comment by acesu1988** [comment]
@alseambusher 

i hava same issue in macos sierra 10.12.3, node v4.2.1.

**Comment by russlamb** [comment]
OS: raspian jessie, 
installed crontab through npm

**Comment by alseambusher** [comment]
Can you please give me the output of `node -e "console.log(process.versions.v8)"` after executing in the terminal.

**Comment by russlamb** [comment]
the output of that command is:
4.5.103.37

**Comment by russlamb** [comment]
The output of that command is:
4.5.103.35

**Comment by alseambusher** [comment]
You need a newer version of v8 that supports "Block Scoped Declarations outside strict mode". However, I have currently fixed it to work with older versions as well. Please get the latest crontab-ui
