### ISSUE TITLE
Get from crontab not working

### ISSUE THREAD

**Issue by phrozendice** [alseambusher/crontab-ui#44]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [X] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
NPM version 3.10.10
Node version v6.10.0

- [X] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [X] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [X] Gone through existing open and closed issues. 

Running on Ubuntu 16.04.2 LTS, I have existing jobs as shown with crontab -l

0	8	*	*	1,2,3,4,5 /home/ubuntu/scripts/start.sh
0	18	*	*	1,2,3,4,5 /home/ubuntu/scripts/stop.sh

When I click "Get from crontab" and then Ok, nothing happens :/

Love the idea btw! 💯

**Comment by phrozendice** [comment]
here is a quick screen capture of the issue https://cl.ly/0v13302o3g3x

**Comment by alseambusher** [comment]
Hi @phrozendice,
It looks like I haven't taken care of "tabs" while parsing existing crontab. Will fix this in the next release.
Thanks

**Comment by phrozendice** [comment]
Thanks,!I was actually testing it live yesterday and I can't seem to get the crons to work/run, I removed the crontabs from the system via crontab -e and added them via crontab-ui, they didn't run, I tried verifying with crontab -l and its empty, any suggestions? should I open a new issue?

**Comment by alseambusher** [comment]
Did you click on "save to crontab" ?

**Comment by phrozendice** [comment]
yes it works, thanks
