### ISSUE TITLE
Can't access it from browser

### ISSUE THREAD

**Issue by pesseyjulien** [alseambusher/crontab-ui#48]
Finally managed to install crontab-ui correcty. 
I'm running it from pm2, and configured a nginx server so I can access it from a browser but I'm getting an empty page => http://admintest.mashup-web.com/crontab

Any idea why ?

Thanks,
julien

**Comment by k0nsl** [comment]
What version of nginx are you running and what does your nginx configuration look like?

**Comment by pesseyjulien** [comment]
nginx version: nginx/1.11.9

And I have just added this to a working virtual server config file :
     
location /crontab {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:8000;
    }

**Comment by k0nsl** [comment]
I'm not sure why it doesn't work for you. I just installed a copy of crontab-ui on my Alpine linux (version `3.5.0`) and I ran it behind nginx `1.10.3`, with the following configuration:

`crontab-ui.conf`:
```
server {
        root /usr/share/nginx;
        listen 127.0.0.1:80;
        server_name k0nsl.org;
        index index.html index.htm index.php;

        #include /etc/nginx/cloudflare-realip.conf;
        #include /etc/nginx/cloudflare-allow.conf;
        #deny all;

location / {
        recursive_error_pages on;

        error_page 500 502 503 504 403 /custom_50x.html;
        location = /custom_50x.html {
                root /usr/share/nginx;
                internal;
        }

        proxy_intercept_errors on;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forward-Proto http;
        proxy_set_header X-Nginx-Proxy true;

        proxy_redirect off;

}
}
```

It might make a difference if you swap out `localhost´ with `127.0.0.1`. Try it and report back.

**Comment by pesseyjulien** [comment]
Found the problem, it did not like the '/crontab'. If I change my location config to just '/' it's displaying something.

**Comment by k0nsl** [comment]
Aha. I'm glad you managed to solve it, @pesseyjulien.

**Comment by pesseyjulien** [comment]
yep, thanks for your help !
