### ISSUE TITLE
import changing cron format

### ISSUE THREAD

**Issue by Muneer94** [alseambusher/crontab-ui#49]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues.

**Comment by Muneer94** [comment]
After creating Cron job when I clicked import to crontab, the format totally changed it is adding log location to the Cron for standard error etc., is there a way to disable it so that the cron format should be the same as what I have created from GUI?

**Comment by alseambusher** [comment]
Yes it is possible. But not by default. Edit this [line](https://github.com/alseambusher/crontab-ui/blob/master/crontab.js#L86).
