### ISSUE TITLE
The requested URL could not be retrieved

### ISSUE THREAD

**Issue by simran66** [alseambusher/crontab-ui#50]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

I am not able to access crontab ui in browser. I have run it on a remote server and am trying to acces it using RemoteIP:port. I have also tried changing the port to 1234 but still the same issue.

curl 127.0.0.1:1234 returns proper response but nothing in browser. all ports are open on the server for global access. Any clue?

**Comment by alseambusher** [comment]
As `curl 127.0.0.1:1234` seems to be working, I think the problem lies with accessing that port from outside. Try `telnet <RemoteIP> <port>`
