### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by salamtura** [alseambusher/crontab-ui#51]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

<img width="568" alt="screen shot 2017-05-14 at 00 24 01" src="https://cloud.githubusercontent.com/assets/5646375/26029990/e1d8913e-383b-11e7-9300-e47d7cd38dc0.png">

Any help with this please.

Thanks

**Comment by alseambusher** [comment]
please download and install the latest [node](https://nodejs.org/en/download/current/).
