### ISSUE TITLE
failed to serve the static file on NGINX

### ISSUE THREAD

**Issue by AssignmentNTU** [alseambusher/crontab-ui#53]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [ ] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [ ] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [ ] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [ ] Gone through existing open and closed issues.

**Comment by AssignmentNTU** [comment]
Hi, I try your module, It is working fine except with the js and css file, I check your code that you used <script src="Jquery.js"> directly, which means If I put the non-found file in the root, There should be no error right ??

**Comment by alseambusher** [comment]
It serves it from [https://github.com/alseambusher/crontab-ui/tree/master/public/js](/public/js/) folder.
