### ISSUE TITLE
Unable to export crontab

### ISSUE THREAD

**Issue by beerendlauwers** [alseambusher/crontab-ui#59]
- `npm --version`: 5.3.0
- `node --version`: v8.6.0

Scenario:
- Go to the web UI.
- Press the "Export" button.

Expected: Crontab is downloaded

Actual: JSON that says `{"message":"mime.lookup is not a function"}`

**Comment by alseambusher** [comment]
This has been fixed in the latest release. Thanks for submitting the issue :)
