### ISSUE TITLE
Adding a slack or email option

### ISSUE THREAD

**Issue by daniyel** [alseambusher/crontab-ui#6]
Hi.

It would be nice if you could add a slack hook or some emailing option after the cron job has finished or failed.

Best regards.

**Comment by alseambusher** [comment]
Thanks for the suggestion! Will add this soon.

**Comment by keviny86** [comment]
@alseambusher any news on this?

**Comment by edgiru** [comment]
interested

**Comment by alseambusher** [comment]
Adding [mail option](https://github.com/alseambusher/crontab-ui/blob/v0.2.3/README/mail.md) (still beta)
