### ISSUE TITLE
Problem with hosting

### ISSUE THREAD

**Issue by vetr0lam** [alseambusher/crontab-ui#60]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [*] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [*] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [*] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [*] Gone through existing open and closed issues. 

I have a problem with hosting of crontab ..i installed nginx, modified the default file but when i type the ip of remote server i only get "welcome" nginx page

**Comment by alseambusher** [comment]
Assuming you have modified the file correctly, you need to restart nginx.

**Comment by vetr0lam** [comment]
I put <a href="https://github.com/alseambusher/crontab-ui/blob/master/README/nginx.md">this</a> at the end of `/etc/nginx/sites-available/default` file and reloaded nginx with `/etc/init.d/nginx reload`
