### ISSUE TITLE
Data File Corrupt error

### ISSUE THREAD

**Issue by Izzy87** [alseambusher/crontab-ui#61]
Hello, I'm still getting used to Ubuntu so forgive my likely visible ignorance, I'm trying to learn, heh.
I recently installed crontab-ui on my Ubuntu v16.04.3 LTS, and while it initially worked it has suddenly faltered only a few days later since installation (not sure what caused it).

Running NPM v5.5.1, Node v8.7.0. My Crontab-UI folder is not at `/usr/lib/node_modules/crontab-ui` but instead `/usr/local/lib/node_modules/crontab-ui`.

The error I receive is detailed below when attempting to run `crontab-ui` at Terminal:
> Node version: 8.7.0
> Crontab UI is running at http://127.0.0.1:8000
> /usr/local/lib/node_modules/crontab-ui/crontab.js:14
> 	if (err) throw err; // no hope, just terminate
> 	         ^
> 
> Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
>     at Persistence.treatRawData (/usr/local/lib/node_modules/crontab-ui/node_modules/nedb/lib/persistence.js:242:11)
>     at /usr/local/lib/node_modules/crontab-ui/node_modules/nedb/lib/persistence.js:281:38
>     at tryToString (fs.js:514:3)
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)

Crontab-ui never automatically launched at system boot by default (not sure if this is typical), so I decided to add it to my /etc/crontab to launch just after a daily scheduled reboot; with a regular user login (not root). This is the only thing I can think of that may have broken it.

I've tampered with one of the files to add the `http basic_authorisation` stuff, and used Apache Tools to create the encrypted password file. I also installed NGINX to proxy and access externally. Both of these were working fine though before the problem.

The only other thing I can report is, when I initially tried to import crontab using the UI's web interface, it didn't import `/etc/crontab` but another file from somewhere else on the system (don't know where) which only contained one command (I recognised it as part of another application we had installed in the past). I think that cron entry is now lost/deleted because I couldn't import anything after that - even if I browsed for `/etc/crontab`, it didn't seem to accept it.

It's all quite strange to me! I appreciate your time & support, I tried to use `sudo npm uninstall crontab` to maybe start fresh but it didn't seem to do anything...

**Edit:** I should probably clarify one thing, although crontab-ui was installed and operating, I never actually got around to solving the issue of importing my crontab job list, I experienced this application error before I had a chance to actually "use" crontab-ui. Maybe the failed import attempts is what nuked it...

**Comment by alseambusher** [comment]
Try reinstalling 
```shell
sudo npm uninstall -g crontab-ui
sudo npm install -g crontab-ui
````

**Comment by Izzy87** [comment]
Following these commands, the application successfully uninstalls, and then (re)installs again.

> manager@Cellar:~$ sudo npm uninstall -g crontab-ui
> removed 95 packages in 1.615s
> manager@Cellar:~$ sudo npm install -g crontab-ui
> /usr/bin/crontab-ui -> /usr/lib/node_modules/crontab-ui/bin/crontab-ui.js
> /usr/bin/crontab-ui-mailer -> /usr/lib/node_modules/crontab-ui/bin/crontab-ui-mailer.js
> + crontab-ui@0.3.2
> added 95 packages in 7.335s

Unfortunately though, I continue to receive the same error as originally posted.

I'm not sure which data file is corrupt, but any chance it's one that can be deleted and then be automatically re-created by NPM or Crontab-UI?

Thanks for your assistance.
