### ISSUE TITLE
Request never end on docker mode

### ISSUE THREAD

**Issue by marlonwc3** [alseambusher/crontab-ui#64]
https://github.com/alseambusher/crontab-ui/blob/1f06112a6a64e6a1f0724afe0ce46e807cea4988/crontab.js#L127

When the application is not running on docker (CRON_IN_DOCKER is defined), 
the flow will skip this if and will never call the callback() function that is the responsible for finish the request, so the client will see a pending request and after the pre-defined timeout he is going to see a error like ERR_EMPTY_RESPONSE. 
This behavior can be visualized running the app on docker, opening the Network Mode on developer tool (chrome), and clicking on 'Save to crontab' button.

Creating the 'else' side of this expression and calling the callback its a solution.

**Comment by alseambusher** [comment]
Thanks for reporting this. I have fixed this in the latest release.
