### ISSUE TITLE
Cant open web

### ISSUE THREAD

**Issue by alreadylostmyself** [alseambusher/crontab-ui#68]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

My issue is i started crontab-iu, but it's not avalible when im try open it on my browser.
My iptables is disabled, so.. i dont know how to fix it

**Comment by alseambusher** [comment]
Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)

**Comment by alreadylostmyself** [comment]
Ofc i runned crontab as `root`
