### ISSUE TITLE
localhost:8000 not accessible

### ISSUE THREAD

**Issue by itsmejainh** [alseambusher/crontab-ui#7]
Hi, 

I just finished installing crontab-ui on one of the server machine. Command "crontab-ui" says - Crontab UI is running at localhost:8000

But, using IP address on other machine which is on same network, I can't access Crontab UI. Is there something which I am missing ? Do I need to update crontab-ui config to specify IP address instead of localhost. 

Also, I couldn't locate conf file. 

thanks.

**Comment by itsmejainh** [comment]
Also, I don't see any logs or error messages.

**Comment by itsmejainh** [comment]
Please ignore this, as I was able to figure out the issue. thank you.

**Comment by alseambusher** [comment]
You have to open the port if you are hosting it on a server to be able to access it elsewhere.
