### ISSUE TITLE
Execute commands within a Docker container

### ISSUE THREAD

**Issue by ebuildy** [alseambusher/crontab-ui#71]
"Using Docker version of crontab-ui, I want to execute a command on other Docker container". 

- Add Docker CLI in the Docker crontab-ui container
- Share Docker socket when running ``-v /var/run/docker.sock:/var/run/docker.sock``
- Support Docker "runner" in crontab-ui web UI

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues.

**Comment by alseambusher** [comment]
What are you trying to do? Using crontab-ui in one docker to control another docker container?

**Comment by ebuildy** [comment]
Yes, to execute code in another Docker container.

**Comment by alseambusher** [comment]
Unfortunately it is not possible with this. Sorry.

**Comment by dengxufan** [comment]
@ebuildy consider as following:

``` dockerfile
FROM library/docker:stable
RUN   apk --no-cache add \
      wget \
      curl \
      nodejs \
      supervisor
RUN npm install -g crontab-ui
EXPOSE 8000
ENV HOST=0.0.0.0
ENTRYPOINT ["crontab-ui"]
```
