### ISSUE TITLE
Like most dockerized apps, this defaults to UTC...

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [alseambusher/crontab-ui#78]
However, many if not all of my scripts only make sense with local time. It would be nice if "New" button dialog had a toggle between local and utc. On the backend it could translate these to UTC anyway. This might be a javascript-only fix.

Additionally, there would also need to be a saved setting for just what local tz is. And maybe even a clock on the webpage showing it.

**Comment by rumd3x** [comment]
Setting environment var TZ=America/Sao_Paulo also doesn't work.

**Comment by caco3** [comment]
Yes, please add this missing feature!

Also it would be great if it would follow daylight saving time (see https://en.wikipedia.org/wiki/Daylight_saving_time)

**Comment by alseambusher** [comment]
I just tested this and it seems to work:
```bash
docker run -e TZ=America/Los_Angeles -p 8000:8000 alseambusher/crontab-ui:0.3.12  
```

**Comment by alseambusher** [comment]
@rumd3x setting env works if you do it as I mentioned above

![image](https://user-images.githubusercontent.com/1242542/84060287-94f06000-a9d9-11ea-9788-2fa4585519f1.png)
