### ISSUE TITLE
no response from localhost:8000

### ISSUE THREAD

**Issue by JayMiao** [alseambusher/crontab-ui#8]
I really need this cool project. But after I installed it, there is nothing return from localhost:8000(or 127.0.0.1:8000).   Is there a log where i can check the status ?
![image](https://cloud.githubusercontent.com/assets/3090408/15563145/7e7579a4-2338-11e6-9671-e1a6365f5c40.png)
![image](https://cloud.githubusercontent.com/assets/3090408/15563152/8ade6e6c-2338-11e6-9f60-15895e7b1797.png)

**Comment by alseambusher** [comment]
@JayMiao looks like you don't have the permissions to run it. You can either 
Change the ownership of node_modules folder to jaymiao like this:
`sudo chown -R jaymiao /usr/local/lib/node_modules`

OR

Run crontab-ui with sudo (Not recommended unless you want to run crontab-ui as root)
