### ISSUE TITLE
Sending E-mail

### ISSUE THREAD

**Issue by thytetgc** [alseambusher/crontab-ui#81]
I already configured it as described in http://lifepluslinux.blogspot.com/2017/03/introducing-mailing-in-crontab-ui.html, I already created ln -s / usr / bin / node / usr / local / bin / node , I still do not get the emails

What do I do?

**Comment by alseambusher** [comment]
1. Are you sure that your transporter and mail config right?
2. Does your network block smtp protocol. Try [nodemailer](https://nodemailer.com/about/) separately and see if it works for you.

**Comment by thytetgc** [comment]
Thanks for the feedback.

This solved:

> ln -s /usr/bin/node /usr/local/bin/node
