### ISSUE TITLE
crontab-ui messing up system crontab

### ISSUE THREAD

**Issue by druuhl** [alseambusher/crontab-ui#84]
The crontab-ui is very messy to the system crontab 
Nogo is:
 - removing comments from the crontab - better is to set/change this in the gui

 - Force logging if not needed - cron sends a mail if stdout or stderr is happen and this makes the crontab unreadable

 - System root Service as Webfrontend - actual crontab-gui works only for root after installation, not for an unprivileged (Changeing the rights on the folder /usr/lib/node_modules/crontab-ui/crontabs to 777 fix that, so i can run this as an other user)

crontab-gui is fine, but actual not usable for dual use of crontab / gui

**Comment by alseambusher** [comment]
I agree. It is hard to make it better for dual use-case.
