### ISSUE TITLE
Cannot save external access to GUI

### ISSUE THREAD

**Issue by charliejsford** [alseambusher/crontab-ui#87]
I have used the cmd:

`HOST=0.0.0.0 PORT=9000 crontab-ui`

Where host = my server IP but as soon as I exit SSH, its not saving and I am unable to access crontab-ui

**Comment by alseambusher** [comment]
What do you mean? Just like any program, If it is running in the foreground, it wouldn't work once you close the shell. Either run it as a service or use tmux/pm/screen.

**Comment by charliejsford** [comment]
Hi, apologies I'm new to this and only know the basics.

How would I run Crontab-ui as a service, please?

**Comment by alseambusher** [comment]
checkout http://pm2.keymetrics.io/

**Comment by charliejsford** [comment]
Any chance you can help with how to use that?

**Comment by JayBird707** [comment]
I'm not sure why you want to run crontab-ui as a service it creates all the required files.  Are you clicking the "Save to crontab" button?

**Comment by charliejsford** [comment]
Maybe I have the wrong idea of the crontab-ui.

The problem I have is, how do I access crontab-ui via the GUI without having to SSH in each time and run it?

**Comment by JayBird707** [comment]
You should not have to SSH at all.
1- Open terminal and type crontab-ui and press enter.
You should see something like this:

Node version: 8.10.0
Crontab UI is running at http://127.0.0.1:8000

The http://127.0.0.1:8000 should actually be a hyperlink so when you hover your mouse over it you can see it get underlined and the cursor changes to a hand or something.  Click on it and your browser will open with the crontab-ui GUI.

**Comment by charliejsford** [comment]
Yes, that it what comes up when i type crontab-ui but if you browse to 127.0.0.1:8000, my PC is trying to access itself (127.0.0.1 is a loopback)

The server running crontab-ui is a hosted server so is not local to me

**Comment by charliejsford** [comment]
can someone help please?
