### ISSUE TITLE
How to install locally without internet? 

### ISSUE THREAD

**Issue by imvieira** [alseambusher/crontab-ui#88]
Hi, 
My test machine does not have internet connection. I would like to know how to install the tool locally without internet? 
If I remember well, I saw npm will fetch remote modules. The same happens with docker repositories. 
Thank you

**Comment by alseambusher** [comment]
You can build a docker image and try exporting and importing

Ref: [https://docs.docker.com/engine/reference/commandline/export/](https://docs.docker.com/engine/reference/commandline/export/)
