### ISSUE TITLE
ui suggestions

### ISSUE THREAD

**Issue by dkebler** [alseambusher/crontab-ui#89]
Super thx for your efforts.  I have a number of linux boxes on my network that need to start cron jobs for backup etc and this is the easiest way to management them from one place.

To make things a bit more intuitive here's a few suggestions to the ui
IHMO it makes more sense that a cronjob is either enabled or disabled  (I used to just do this by commenting in the crontab file.)  So maybe each cronjob should have an enabled check box.  That would mean you could remove the "stop" button which kinda implies that it would stop a job ran manually with the "run" button.    The run button since it has no a tool tip should maybe say "Run Now" which is just a way to test the job not enable with the cron timer.   One could even color background green of any enabled job.  Also with enabled field one could sort on either enabled or disabled jobs.

I assume the "save to crontab" saves any jobs which are not "stopped".  So instead drop that button and save whenever a enable checkbox changes state.  It would be nice if the crontab file was nosql or json so it would be CRUD compatible but being a flat text file makes management a pain  (or maybe better to use the cron.d is that what you are doing?).   

If you are looking for a better more powerful way (and IMO way easierway) to write your UI consider vuejs and the quasarframework.  With these two I can whip out a great looking responsive ui with great layouts and things like tooltips easily.  Tool tips really help guide users without documentation.   https://quasar-framework.org/

Once again Thx!

**Comment by alseambusher** [comment]
Thanks for your feedback. All of these are good points. I will see what I can incorporate in my free time :)

**Comment by CausticD** [comment]
I liked some of your suggestions. I have forked this repo, and trying some things myself. https://github.com/CausticD/crontab-ui
