### ISSUE TITLE
Crontab-UI works only manually

### ISSUE THREAD

**Issue by Co7omo** [alseambusher/crontab-ui#91]
Jobs works only if ran manually.

Also no log is written even when ran manully

**Comment by Lalarian** [comment]
Hello!

I'm having the same problem right now!
I added a job and it's working fine when I click on run.
The time column tells me it should be executed in a minute - but it won't.

crontab-ui does not run with sudo, because it needs write access to 

> /usr/local/lib/node_modules/crontab-ui/crontabs/

The crontab entries made with the ui are onyl added to root's crontab. Is this the way it should be done?

**Comment by rwibowo** [comment]
Any workaround to fix this issue ?

**Comment by rwibowo** [comment]
If you run crontab-ui using CentOS, you need to change CRON_PATH to /var/spool/cron
It is working for me, and don't forget to press green "Save to crontab" button.

`export CRON_PATH=/var/spool/cron`

**Comment by alseambusher** [comment]
@Co7omo What do you mean by "If ran manually" ?

@rwibowo Thanks for the info!

**Comment by robot110011** [comment]
same here. script only run if I press 'run' manually in the console

**Comment by horkko** [comment]
Hi,

I've got similar problem, I can add/edit/delete jobs from the interface, however, as shown in the image attached, my job is always with 'RUN' button looks like the script is not started at all. I can run it manually by pressing the 'RUN' button, the jobs is executed, but not automatically.

![screenshot 2019-01-29 at 17 54 12](https://user-images.githubusercontent.com/9282917/51925432-557e3080-23ef-11e9-9c75-3233bd44e18b.png)

I've started `crontab-ui.js` with `pm2` as suggested in the documentation to have it as a service and it look like is running ok without error(s) (see below)

![screenshot 2019-01-29 at 17 59 22](https://user-images.githubusercontent.com/9282917/51925591-abeb6f00-23ef-11e9-9960-0d63752fbabb.png)

Last but not least, there is not log(s) created under `crontab-ui/crontabs/logs` directory. Even if the `enable logging` checkbox is checked.

Any clue over these issues? I really like your tool, its great help for our people.

Thanks in advance

**Comment by vicwomg** [comment]
I was experiencing this issue as well, turns out with cron you must specify the full path to your binary unless you specify PATH (e.g. "/usr/bin/curl" instead of "curl"). Also, there are disallowed chars in cron such as "%" which will render as newline. I was seeing this since my curl'url contained HTML escaping. You will need to escape them in the crontab file (ex. "\%" )

**Comment by Nguyenanh** [comment]
@Co7omo Hey.
you can run it deamon with `pm2`. At command run `env HOST=0.0.0.0 pm2 start crontab-ui -- --autosave`. It work for me.

**Comment by GregoryVillareal** [comment]
I am experiencing this issue to date. 

node version: 12.13.0
npm version: 6.12.0

I am able to create jobs and click run to fire the job no problem; however, a ping to google scheduled for every minute never gets ran. 

The first issue I come across in this process is attempting to use pm2 command `pm2 start crontab-ui` pm2 error log for this command is as follows:
![image](https://user-images.githubusercontent.com/36932945/68316919-3e5c2580-0088-11ea-9d78-a4834f077def.png)

Secondly, I may click the run button to get a ping to google when running the UI without pm2. 
At each minute with my cron statement I expect a ping every minutes but it seems to be doing nothing. 

Here I expect to print out by 11:34 and nothing occurred:
![image](https://user-images.githubusercontent.com/36932945/68317606-68faae00-0089-11ea-82b9-53dd53c9170e.png)


Any potential update with this issue/how to get it working for demonstration purposes.

**Comment by alseambusher** [comment]
@GregoryVillareal Did you click `save to crontab`?

**Comment by GregoryVillareal** [comment]
@alseambusher Yes, saving to crontab results in this error: 
![image](https://user-images.githubusercontent.com/36932945/68419163-b64d4d00-0167-11ea-9378-4b3da7369e7a.png)

I've tried to find the log file; though it isn't shown in this directory: 
![image](https://user-images.githubusercontent.com/36932945/68419356-1217d600-0168-11ea-9a6e-66d7f1188f18.png)

**Comment by alseambusher** [comment]
@GregoryVillareal are you using windows? This works only on linux/unix and mac like OSes.

**Comment by caco3** [comment]
For me it was because I forgot to save to crontab :(
Not very intuitive! Why can't this be done when ever one edits a job?

**Comment by alseambusher** [comment]
@caco3 you can use the --autosave option if you don't want to click on 'save to crontab'.

I made it optional because if this was default and you make some mistake while adding a job, it would mess up all other running jobs. This would be bad in a production environment.

**Comment by abdatta** [comment]
@alseambusher Can you add a marker for each unsaved but edited cronjob. That helps one to realise that it isn't saved. It took me some time to figure out what was wrong, and that I have to press "Save to Crontab" every time.

**Comment by HMS-WebHub** [comment]
> @alseambusher Yes, saving to crontab results in this error:
> ![image](https://user-images.githubusercontent.com/36932945/68419163-b64d4d00-0167-11ea-9378-4b3da7369e7a.png)
> 
> I've tried to find the log file; though it isn't shown in this directory:
> ![image](https://user-images.githubusercontent.com/36932945/68419356-1217d600-0168-11ea-9a6e-66d7f1188f18.png)

I hade same problem, what solved it was to set "HOME=/home/cronjob" in environment variable
i use systemd to run this and have following in the file "/etc/systemd/system/crontab-ui.service"
> [Unit]
> Description=Crontab-ui Server
> After=network.target syslog.target
> 
> [Service]
> Type=simple
> ExecStart=/home/cronjob/node/bin/node /home/cronjob/node_modules/crontab-ui/bin/crontab-ui
WorkingDirectory=/home/cronjob/
> Restart=always                                               # If set to always, the service will be restarted regardless of whether it exited cleanly or no$
> RestartSec=10                                                # Restart service after 10 seconds if node service  crashes
> StandardOutput=syslog                                        # Output to syslog
> StandardError=syslog                                         # Output to syslog
> SyslogIdentifier=Crontab-UI
> User=cronjob
> Group=cronjob
> Environment=HOST=cron02.dc01
> Environment=PORT=8000
> Environment=BASIC_AUTH_USER=****
> Environment=BASIC_AUTH_PWD=****
> Environment=HOME=/home/cronjob
> 
> [Install]
> WantedBy=multi-user.target

**Comment by NamanNacedo** [comment]
Hello, 
I have exactly the same, I tried every solution and still the same, this is my command:
cd /home/user/Documents/health-service && /usr/bin/dotnet test --filter FullyQualifiedName\~Tests.SeleniumTests.Tests.AuthenticationTest.AuthenticationDesktop Tests/Tests.csproj

If I click on Run it works but not automaticly, I set to run this command every 2 minutes
something wrong with my command? Only with the root right you can use this command but crontab-ui is open with the root right also
Someone can help me?

**Comment by alseambusher** [comment]
@HMS-WebHub you can find the log in the browser console.

**Comment by benjcabalona1029** [comment]
Hi, I have encountered this issue, and was able to fix it by doing the following steps. 

I'm using a MAC but I think the fix is similar to other platform as well.

- Ensure that you are saving to crontab.
- When you first tried to run `crontab-ui` and you get a permission error, do not just run the command using `sudo` instead, change the permission of `crontab-ui/crontabs` e.g. `sudo chmod 777 /usr/local/lib/node_modules/crontab-ui/crontabs`
- Change the permission of the directory where your crontab file is saved, in a mac that is `sudo chmod 777 /tmp/crontab`

Just try to read the logs when you run `crontab-ui` as that is extremely useful.

I will try this in a Ubuntu and RHEL VM over the weekend, and will get back here to update this comment.

I hope it helps someone in the future.

**Comment by 13Dima13** [comment]
And even more pain if you install it in docker container: /bin/sh: apt-get: not found, sh not found, sudo not found...

**Comment by SideeqShafiRather** [comment]
> @GregoryVillareal Did you click `save to crontab`?

You need to explicitly click on `save to crontab` in case you make any change to any listed cron. so Ideally all the listed tabs should also be present in Environment Variables tab...Attaching Screenshot 
<img width="960" alt="savetoCron" src="https://user-images.githubusercontent.com/52281031/212625737-1553b8cd-16a9-4bb1-90eb-402fa623adc4.png">
So finally it worked for me as well, I am using Windows 10
