### ISSUE TITLE
Execute job only once

### ISSUE THREAD

**Issue by ronaldocorrea** [alseambusher/crontab-ui#97]
Make sure these boxes are checked( - [x] ) before submitting an issue.

- [x] Running latest npm and node? (Run `npm --version` and `node --version`). Get the latest nodejs [here](https://nodejs.org/en/download/).
- [x] The `node_modules` folder has right permissions (Run `ls -ld $(npm root -g)/crontab-ui`)
- [x] Read [issues.md](https://github.com/alseambusher/crontab-ui/blob/master/README/issues.md)
- [x] Gone through existing open and closed issues. 

Hi all,

I was wondering if it would be possible to implement a new feature which would be very handy. This feature will allow the user to chose if the scheduled job should run only once. Which means that after the job run, the attribute "stopped" will be updated to "true".

What do you guys think about this feature?

Kind regards

**Comment by yuminatwca** [comment]
I am searching for answers about this as well.

But i guess this can be done via database and it would need a little bit of coding.

Say, we need to check the database whether it has un-executed jobs. If it does, we checkout whether it's time to execute it. If it does, we execute this specific command.

something like that, which I haven't tested yet.

**Comment by alseambusher** [comment]
The only way you can do this is to set up the fields exactly. For example, you want to run `At 04:05 on 4th  December`.

```
5 4 4 12 * command
```

However, this will run once in a year. That is good enough right?
